# ADM HW 1
#### Yoanna Efimova

In [1]:
import numpy as np
import pandas as pd

# Problem 1

# Introduction (all – total: 7 - max points: 75)
https://www.hackerrank.com/domains/python/py-introduction

##### Say "Hello, World!" With Python

In [1]:
if __name__ == '__main__':
    print("Hello, World!")

Hello, World!


##### Python If-Else

In [2]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    if n%2 != 0:
        print("Weird")
    else:
        if (n>=2) and (n<=5):
            print("Not Weird")
        elif (n>=6) and (n<=20):
            print("Weird")
        elif n>20:
            print("Not Weird")

3
Weird


##### Arithmetic Operators

In [4]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b)
    print(a-b)
    print(a*b)


3
5
8
-2
15


##### Python: Division

In [5]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a//b)
    print(a/b)


3
5
0
0.6


##### Loops

In [6]:
if __name__ == '__main__':
    n = int(input())
    for i in range(n):
        print(i**2)


3
0
1
4


##### Write a function

In [7]:
def is_leap(year):
    leap = False
    
    # Write your logic here
    
    if year % 4 == 0:
        if year % 100 != 0:
            leap = True
        elif (year % 100 == 0) and (year % 400 == 0):
            leap = True
        
    return leap

year = int(input())
print(is_leap(year))

1990
False


##### Print Function

In [8]:
if __name__ == '__main__':
    n = int(input())
    for i in range(1,n+1):
        print(i, end='')


3
123

# Data types (all – total: 6 - max points: 60)
https://www.hackerrank.com/domains/python/py-basic-data-types

##### List Comprehensions

In [26]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    
    # new_list=[]
    # for i in range(x+1):
    #     for j in range(y+1):
    #         for k in range(z+1):
    #             new_list.append([i,j,k])
                
    # final_list = []
    # for l in new_list:
    #     if sum(l) != n:
    #         final_list.append(l)
    
    
    new_list = [[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1)]
    
    final_list = [l for l in new_list if sum(l) != n]
    
    print(final_list)             

1
1
2
3
[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 2]]


##### Find the Runner-Up Score!

In [11]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    arr = list(arr)
    arr.sort()
    unique_values = list(set(arr))
    runner_up = unique_values[-2]
    print(runner_up)


5
2 3 6 6 5
5


##### Nested Lists

In [13]:
if __name__ == '__main__':
    list_students = []
    for _ in range(int(input())):
        listB = []
        name = input()
        listB.append(name)
        score = float(input())
        listB.append(score)
        list_students.append(listB)
     
    if (len(list_students) < 2):
        print('')
    elif (len(list_students) > 5):
        print('')
    else:       
        list_students.sort(key = lambda x: x[1])
        
        scores = [] 
        for i in list_students:
            scores.append(i[1])
        unique_scores = set(scores)
        
        if len(unique_scores) == 1:
            print('')
        else:
            unique_scores = list(unique_scores)
            second_lowest = unique_scores[1]

            namesSL = []
            for i in list_students:
                if i[1] == second_lowest:
                    namesSL.append(i[0])
            
            namesSL.sort()
            for i in namesSL:
                print(i, end='\n')


5
Harry
37.21
Berry
37.21
Tina
37.2
Akriti
41
Harsh
39
Berry
Harry


##### Finding the percentage

In [12]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    
    avg = sum(student_marks[query_name]) / len(student_marks[query_name])
    avg = "{:.2f}".format(avg)
    print(avg)


3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika
56.00


##### Lists

In [25]:
if __name__ == '__main__':
    N = int(input())
    list_commands = []
    
    for i in range(N):
        command = str(input())
        list_commands.append(command)
        
    if 'remove' in list_commands[0]:
        print('')
    elif 'pop' in list_commands[0]:
        print('')
    else:
        list_commands2=[]
        for i in list_commands:
            list_commands2.append(" ".join(i.split()))
        
        my_list = []
        for c in list_commands2:
            if 'insert' in c:
                separated_comm = c.split()
                index = int(separated_comm[1]) 
                elem = int(separated_comm[2])
                my_list.insert(index,elem)
            elif 'print' in c:
                print(my_list)
            elif 'remove' in c:
                # remove the first occurance of integer e
                e = int(c[7:])
                my_list.remove(e)
            elif 'append' in c:
                new_elem = int(c[7:])
                my_list.append(new_elem)    
            elif 'sort' in c:
                my_list.sort()
            elif 'pop' in c:
                my_list = my_list[:-1]
            elif 'reverse' in c:
                my_list.reverse()


4
append 1
append 2
insert 3 1 
print
[1, 2, 1]


##### Tuples

In [18]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    integer_list = list(integer_list)
    
    t = tuple()
    for i in integer_list:
        t += i,
    
    print(hash(t))


2
1 2
-3550055125485641917


# Strings (all – total: 14 - max points: 220)
https://www.hackerrank.com/domains/python/py-strings

##### sWAP cASE

In [10]:
def swap_case(s):
    if (len(s) <= 0) or (len(s) > 1000):
        string = ''
        return string
    else:     
        new_list = []
        for i in range(len(s)):
            if s[i].isupper() == True:
                new = s[i].lower()
                new_list.append(new)
            elif s[i].islower() == True:
                new = s[i].upper()
                new_list.append(new)
            else:
                new_list.append(s[i])
        
        new_string = ''
        for i in new_list:
            new_string += i        
    
    return new_string

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

HackerRank.com presents "Pythonist 2".
hACKERrANK.COM PRESENTS "pYTHONIST 2".


##### String Split and Join

In [12]:
def split_and_join(line):
    # write your code here
    list_char = line.split(" ")
    new_string = "-".join(list_char)
    return new_string

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

this is a string
this-is-a-string


##### What's Your Name?

In [15]:
#
# Complete the 'print_full_name' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING first
#  2. STRING last
#

def print_full_name(first, last):
    # Write your code here
    sentence = 'Hello ' + first + ' ' + last + '! You just delved into python.'
    print(sentence)

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

Yoanna
Efimova
Hello Yoanna Efimova! You just delved into python.


##### Mutations

In [16]:
def mutate_string(string, position, character):    
    new_string = string[:position] + character + string[position+1:]
    return new_string


if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

abracadabra
5 k
abrackdabra


##### Find a string

In [134]:
def count_substring(string, sub_string):
    if (len(string) < 1) or (len(string) > 200):
        return("")
    else:
        num_occur = 0
        for i in range(len(string)):
            if string[i:].startswith(sub_string):
                num_occur += 1
    
    return num_occur
    
    
if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

ABCDCDC
CDC
2


##### String Validators

In [17]:
if __name__ == '__main__':
    s = input()
    if (len(s) <= 0) or (len(s) >= 1000):
        print('')
    else:
        i = 0
        result1 = False
        while i < len(s):
            if s[i].isalnum() == True:
                result1 = True
                break
            i+=1
        print(result1)
        
        j = 0
        result2 = False
        while j < len(s):
            if s[j].isalpha() == True:
                result2 = True
                break
            j+=1
        print(result2)
        
        k = 0
        result3 = False
        while k < len(s):
            if s[k].isdigit() == True:
                result3 = True
                break
            k+=1
        print(result3)
        
        p = 0
        result4 = False
        while p < len(s):
            if s[p].islower() == True:
                result4 = True
                break
            p+=1
        print(result4)
        
        t = 0
        result5 = False
        while t < len(s):
            if s[t].isupper() == True:
                result5 = True
                break
            t+=1
        print(result5)

qA2
True
True
True
True
True


##### Text Alignment

In [13]:
#Replace all ______ with rjust, ljust or center. 

thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))    

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))


5
    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


##### Text Wrap

In [14]:
import textwrap

def wrap(string, max_width):
    return textwrap.fill(string,max_width)

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

ABCDEFGHIJKLIMNOQRSTUVWXYZ
4
ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ


##### Designer Door Mat

In [262]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

NM = list(map(int, input().split()))
N = NM[0]
M = NM[1]

if (N<=5) or (N>=101):
    print('')
elif (M<=15) or (M>=303):
    print('')
else: 
    num_pattern = 1   
    for i in range(1,N//2+1):
        sign = '.|.' * num_pattern
        num_pattern += 2
        print(sign.center(M,'-'))
    
    print('WELCOME'.center(M,'-'))
    
    num_pattern -= 2
    for j in range(N//2+2,N+1):
        sign = '.|.' * num_pattern
        num_pattern -= 2
        print(sign.center(M,'-'))
        

9 27
------------.|.------------
---------.|..|..|.---------
------.|..|..|..|..|.------
---.|..|..|..|..|..|..|.---
----------WELCOME----------
---.|..|..|..|..|..|..|.---
------.|..|..|..|..|.------
---------.|..|..|.---------
------------.|.------------


##### String Formatting

In [156]:
def print_formatted(number):
    # your code goes here
    if (number<1) or (number>99):
        print("")
    else:
        width_binary_num = len("{0:b}".format(number))
        
        for i in range(1,number+1):
            decimal = str(i)
            octal = "{:o}".format(i)
            hexadecimal = "{:x}".format(i).upper()
            binary = "{0:b}".format(i)
            
            print(decimal.rjust(width_binary_num),octal.rjust(width_binary_num),hexadecimal.rjust(width_binary_num),binary.rjust(width_binary_num))

if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

25
    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001
   18    22    12 10010
   19    23    13 10011
   20    24    14 10100
   21    25    15 10101
   22    26    16 10110
   23    27    17 10111
   24    30    18 11000
   25    31    19 11001


##### Alphabet Rangoli

In [203]:
import string

def print_rangoli(size):
    # your code goes here
    if (size<=0) or (size>=27):
        print("")
    else:        
        alphabet = string.ascii_lowercase
        for i in range(size-1,-1,-1):
            letters = alphabet[size-1:i:-1] + alphabet[i:size]
            letters = "-".join(letters)
            print(letters.center(size*4-3,"-"))

        for j in range(1,size):
            letters = alphabet[size-1:j:-1] + alphabet[j:size]
            letters = "-".join(letters) 
            print(letters.center(size*4-3,"-"))
            
if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

5
--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


##### Capitalize!

In [19]:
#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    s_char = s.replace(" ", "")
    
    if s_char.isalnum() == False:
        name=''
        return name
    elif (len(s) <= 0) or (len(s) >= 1000):
        name = ''
        return name
    else:
        s = s.strip()
        list_name = list(s)

        new_list = [list_name[0].upper()]
        for i in range(1,len(list_name)):
            if list_name[i-1] == ' ':
                new_list.append(list_name[i].upper())
            else:
                new_list.append(list_name[i])
            
        final_name = ''
        for i in new_list:
            final_name += i
            
        return final_name
    

s = input()

result = solve(s)

result

chris alan


'Chris Alan'

##### The Minion Game

Initially I could not pass all test cases so I looked at the Discussion part for different ideas on how to solve the prblem.

In [209]:
def minion_game(string):
    # your code goes here
    if (len(string)<=0) or (len(string)>1000000):
        print("")
    else:
        name_score = {'Stuart':0, 'Kevin':0}
        vowels = ['A', 'E', 'I', 'O', 'U']
        n = len(string)
        
        for i in range(n):
            if(string[i] in 'AEOUI'):
                # there are n number of substrings that start with letter of index i
                name_score['Kevin'] += n - i
            else:
                name_score['Stuart'] += n - i
        
        if name_score['Kevin'] == name_score['Stuart']:
            print("Draw")
        elif name_score['Kevin'] > name_score['Stuart']:
            print("Kevin " + str(name_score['Kevin']))
        else:
            print("Stuart " + str(name_score['Stuart']))

if __name__ == '__main__':
    s = input()
    minion_game(s)

BANANA
Stuart 12


##### Merge the Tools!

In [207]:
import textwrap

def merge_the_tools(string, k):
    # your code goes here
    n = len(string)
    if (n<1) or (n>10000):
        print("")
    elif (k<1) or (k>n):
        print("")
    elif n % k != 0:
        print("")
    else:
        substr = textwrap.wrap(string, k)
        
        for i in substr:
            new_substr = "".join(dict.fromkeys(i))
            print(new_substr)
    

if __name__ == '__main__':
    string, k = input(), int(input())
    merge_the_tools(string, k)

ABACDEFGF
3
AB
CDE
FG


# Sets (all – total: 13 - max points: 170)
https://www.hackerrank.com/domains/python/py-sets

##### Introduction to Sets

In [20]:
def average(array):
    # your code goes here
    
    distinct_heights = set(array)
    total_number = len(distinct_heights)
    
    sum_dist_heights = 0
    for h in distinct_heights:
        sum_dist_heights += h
    
    average = sum_dist_heights / total_number
    return average
    

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


##### No Idea!

In [264]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

nm = list(map(int,input().split()))
n = nm[0]
m = nm[1]

if (n<1) or (n>100000) or (m<1) or (m>100000):
    print('')
else:
    Array = list(map(int,input().split()))
    A = set(map(int,input().split()))
    B = set(map(int,input().split()))
    
    happiness = 0
    for i in Array:
        if i in A:
            happiness += 1
        if i in B:
            happiness -= 1
    print(happiness)
        

3 2
1 5 3
3 1 
5 7
1


##### Symmetric Difference

In [21]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

M = int(input())
arr_M = list(map(int, input().split()))
set_M = set(arr_M)

N = int(input())
arr_N = list(map(int, input().split()))
set_N = set(arr_N)

M_dif_N = set_M.difference(set_N)
N_dif_M = set_N.difference(set_M)

sym_dif = M_dif_N.union(N_dif_M)

list1 = []
for i in sym_dif:
    list1.append(i)
list1.sort()

for j in list1:
    print(j)
 

4
2 4 5 9
4 
2 4 11 12
5
9
11
12


##### Set .add()

In [22]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

N = int(input())
countries = [input() for _ in range(N)]

if (N <= 0) or (N >= 1000):
    print('')
else:
    set_countries = set(countries)
    print(len(set_countries)) 

7
UK
China
USA
France
New Zealand
UK
France
5


##### Set .discard(), .remove() & .pop()

In [42]:
n = int(input())
s = set(map(int, input().split()))  #non-empty set

N = int(input())
commands = [str(input()) for _ in range(N)]


if (n<=0) or (n>=20):
    print('')
elif (N<=0) or (N>=20):
    print('')
else:
    for c in commands:
        if 'pop' in c:
            if len(s) > 0:
                s.pop()
        elif 'remove' in c:
            c = "".join(c.split())
            elem = int(c[-1])
            if len(s) > 0:
                s.remove(elem)
        elif 'discard' in c:
            c = "".join(c.split())
            elem = int(c[-1])
            if len(s) > 0:
                s.discard(elem)  
    
    s_sum = sum(s)      
    print(s_sum)


3
1 1 2
1
remove 1
2


##### Set .union() Operation

In [45]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n = int(input())
set_n = set(map(int, input().split()))

b = int(input())
set_b = set(map(int, input().split()))

union_students = set_n.union(set_b)

if (len(union_students)<=0) or (len(union_students)>=1000):
    print('')
else:
    total_num = len(union_students)
    print(total_num)

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


##### Set .intersection() Operation

In [46]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n = int(input())
set_n = set(map(int, input().split()))

b = int(input())
set_b = set(map(int, input().split()))

union_students = set_n.union(set_b)
stud_both_classes = set_n.intersection(set_b)

if (len(union_students)<=0) or (len(union_students)>=1000):
    print('')
else:
    print(len(stud_both_classes))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


##### Set .difference() Operation

In [47]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n = int(input())
set_n = set(map(int, input().split()))

b = int(input())
set_b = set(map(int, input().split()))

union_students = set_n.union(set_b)
only_english = set_n.difference(set_b)

if (len(union_students)<=0) or (len(union_students)>=1000):
    print('')
else:
    print(len(only_english))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


##### Set .symmetric_difference() Operation

In [48]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

n = int(input())
set_n = set(map(int, input().split()))

b = int(input())
set_b = set(map(int, input().split()))

union_students = set_n.union(set_b)
in_only_1class = set_n.symmetric_difference(set_b)

if (len(union_students)<=0) or (len(union_students)>=1000):
    print('')
else:
    print(len(in_only_1class))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


##### Set Mutations

In [211]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

num_A = int(input())
A = list(map(int, input().split()))

# nummber of other sets
N = int(input())

commands = []
for i in range(N):
    operation = str(input())
    other_list = list(map(int, input().split()))
    if (len(other_list)<=0) or (len(other_list)>=100):
            print('')
            break
    commands.append([operation,other_list])
    
    
if (len(A)<=0) or (len(A)>=1000):
    print('')
elif (len(A)<=0) or (len(A)>=1000):
    print('')
else:
    set_A = set(A)
    for c in commands:
        if "intersection_update" in c[0]:
            set_A.intersection_update(set(c[1]))
        elif c[0][0] == "u":
            set_A.update(set(c[1]))
        elif ("difference" in c[0]) and ("symm" not in c[0]):
            set_A.difference_update(set(c[1]))
        elif "symmetric" in c[0]:
            set_A.symmetric_difference_update(set(c[1]))
        
        
    print(sum(set_A))


16
 1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
38


##### The Captain's Room

In [219]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

from collections import Counter

K = int(input())
rooms_list = list(map(int, input().split()))

if (K<=1) or (K>=1000):
    print('')
else:
    room_nums = Counter(rooms_list)
    cap_room = [k for k,v in room_nums.items() if v==1]
    print(cap_room[0])


5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


##### Check Subset

In [213]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

T = int(input())

if (T<=0) or (T>=21):
    print('')
else:
    lists = []
    for i in range(T):
        A_num = int(input())
        if (A_num<=0) or (A_num>=1001):
            print('')
            break
        A = list(map(int, input().split()))
        A = set(A)
        
        B_num = int(input())
        if (B_num<=0) or (B_num>=1001):
            print('')
            break
        B = list(map(int, input().split()))
        B = set(B)
        
        lists.append([A,B])
        
    for i in range(T):
        print(lists[i][0].issubset(lists[i][1]))

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
1
2
5
3 6 5 4 1
7
1 2 3 5 6 8 9
3
9 8 2
True
False
False


##### Check Strict Superset

In [218]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

A = list(map(int, input().split()))
A = set(A)

if (len(A)<=0) or (len(A)>=501):
    print('')
else:
    n = int(input())
    if (n<=0) or (n>=21):
        print('')
    else:
        other_sets = []
        
        for i in range(n):
            set_i = list(map(int, input().split()))
            set_i = set(set_i)
            if (len(set_i)<=0) or (len(set_i)>=101):
                print('')
                break
            other_sets.append(set_i)
        
        # check whether A is a strict superset of each of the n sets
        result = "True"
        
        for i in range(len(other_sets)):
            if len(other_sets[i]) == len(A):
                result = "False"
                break
            if other_sets[i].issubset(A) == False:
                result = "False"
                break
        
        print(result)

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


# Collections (all – total: 8 - max points: 220)
https://www.hackerrank.com/domains/python/py-collections

##### collections.Counter()

In [225]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import Counter

X = int(input())
if (X<=0) or (X>=1000):
    print('')
else:
    shoes_shop = list(map(int, input().split()))
    shoes = Counter(shoes_shop)
    
    N = int(input())
    
    if (N<=0) or (N>1000):
        print('')
    else:
        customers = []
        for i in range(N):
            size_money = list(map(int, input().split()))
            size = size_money[0]
            money = size_money[1] 
            if (size<2) or (size>20) or (money<20) or (money>100):
                print('')
            else:
                customers.append(size_money)
        
        R_money = 0
        for c in customers:
            if c[0] in shoes.keys():
                if shoes[c[0]] > 0:
                    R_money += c[1]
                    shoes[c[0]] -= 1
        
        print(R_money)


10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55
4 40
18 60
10 50
200


##### DefaultDict Tutorial

In [226]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

from collections import defaultdict

n_m = list(map(int, input().split()))
n = n_m[0]
m = n_m[1]

if (n<1) or (n>10000) or (m<1) or (m>100):
    print('')
else:
    A = [input() for _ in range(n)]
    B = [input() for _ in range(m)]
    
    idx_B_in_A = []
    for word in B:
        indices = []
        if word in A:
            for i in range(len(A)):
                if A[i] == word:
                    indices.append(A.index(A[i], i, len(A))+1)
        else:
            indices.append(-1)
        idx_B_in_A.append(indices)
            
    for l in idx_B_in_A:
        for elem in l:
            print(elem, end=" ")
        print("")
        

5 2
a
a
b
a
b
a
b
1 2 4 
3 5 


##### Collections.namedtuple()

In [227]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

from collections import namedtuple

S = namedtuple('S', 'ID MARKS CLASS NAME')

N = int(input())

if (N<=0) or (N>100):
    print('')
else:
    cols = list(map(str, input().split()))
    if ('ID' not in cols) or ('MARKS' not in cols) or ('CLASS' not in cols) or ('NAME' not in cols) or len(cols)!=4:
        print('')
    else:
        # indices of the columns
        idx_ID = cols.index('ID')
        idx_M = cols.index('MARKS')
        idx_C = cols.index('CLASS')
        idx_N = cols.index('NAME')
                
        students = []
        all_marks = []
        
        for s in range(N):
            person = list(map(str, input().split()))
            Id = person[idx_ID]
            Marks = person[idx_M]
            Class = person[idx_C]
            Name = person[idx_N]
            
            stud = S(ID = Id, MARKS = Marks, CLASS = Class, NAME = Name)
            students.append(stud)
            all_marks.append(int(Marks))
        
        avg_mark = sum(all_marks) / len(students)
        print(avg_mark)

5
MARKS      CLASS      NAME       ID        
92         2          Calum      1        
82         5          Scott      2         
94         2          Jason      3          
55         8          Glenn      4          
82         2          Fergus     5
81.0


##### Collections.OrderedDict()

In [228]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

from collections import OrderedDict

# number of items
N = int(input())

if (N<=0) or (N>100):
    print('')
else:
    items_net_price = OrderedDict()
    all_items = []
    
    for i in range(N):
        item = list(map(str, input().split()))
        item_name = item[:-1]
        item_name = " ".join(item_name)
        item_price = int(item[-1])
        all_items.append([item_name,item_price])
        
    for j in all_items:
        items_net_price[j[0]] = 0
    
    for k in all_items:
        items_net_price[k[0]] += k[1]
    
    for it,pr in items_net_price.items():
        print(it, pr)

9
BANANA FRIES 12
POTATO CHIPS 30
APPLE JUICE 10
CANDY 5
APPLE JUICE 10
CANDY 5
CANDY 5
CANDY 5
POTATO CHIPS 30
BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


##### Word Order

In [231]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import OrderedDict

# number of words
n = int(input())

if (n<1) or (n>100000):
    print('')
else:
    all_words = [input() for _ in range(n)]
    
    # check whether the words are all lowercase
    assert all((w.islower() == True) for w in all_words)
    
    sum_len_words = [sum(len(w) for w in all_words)][0]
    
    if sum_len_words > 1000000:
        print('')
    else:
        # find the number of unique words
        unique_words = set(all_words)
        print(len(unique_words))
        
        words_count = OrderedDict()
        for j in all_words:
            words_count[j] = 0
            
        for k in all_words:
            words_count[k] += 1
    
        for word,count in words_count.items():
            print(count, end=' ')


4
bcdef
abcdefg
bcde
bcdef
3
2 1 1 

##### Collections.deque()

In [232]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import deque

# number of operations
N = int(input())

if (N<=0) or (N>100):
    print('')
else:
    commands = [input().split() for _ in range(N)]
    
    d = deque()
    
    for c in commands:
        if c[0] == 'append':
            d.append(int(c[1]))
        elif c[0] == 'pop':
            d.pop()
        elif c[0] == 'popleft':
            d.popleft()
        elif c[0] == 'appendleft':
            d.appendleft(int(c[1]))
    
    for elem in d:
        print(elem, end = ' ')


6
append 1
append 2
append 3
appendleft 4
pop
popleft
1 2 

##### Piling Up!

In [241]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import deque

# number of test cases
T = int(input())

if (T<1) or (T>5):
    print('')
else:
    cubes = []
    for i in range(T):
        num_cubes = int(input())
        if (num_cubes<1) or (num_cubes>100000):
            print('')
            break
        else:
            sideLengths = deque(map(int, input().split()))
            assert all((j>=1) or (j<2**31) for j in sideLengths)
            cubes.append(sideLengths)
            
    for c in cubes:
        for j in range(len(c)-1):
            if (c[0]>=c[1]) and (c[0]>=c[-1]):
                c.popleft()
            elif (c[-1]>=c[-2]) and (c[-1]>=c[0]):
                c.pop()
            else:
                break
        
        if len(c) <= 1:
            print("Yes")
        else:
            print("No")

2
6
4 3 2 1 3 4
3
1 3 2
Yes
No


##### Company Logo

In [233]:
#!/bin/python3

import math
import os
import random
import re
import sys

from collections import Counter

if __name__ == '__main__':
    s = input()
    if (len(s)<=3) or (len(s)>10000):
        print('')
    elif len(set(s))<3:
        print('')
    else:
        letters_count = Counter(sorted(s))
        
        for l in letters_count.most_common(3):
            print(l[0],l[1])
    

aabbbccde
b 3
a 2
c 2


# Date and Time (all – total: 2 - max points: 40)
https://www.hackerrank.com/domains/python/py-date-time

##### Calendar Module

In [52]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import calendar
# print(calendar.TextCalendar(firstweekday=6).formatyear(2015))


date = list(map(int, input().split()))

if (date[2]<2000) or (date[2]>3000):
    print('')
else:
    day_number = calendar.weekday(date[2], date[0], date[1])
    d = {0: 'MONDAY', 1: "TUESDAY", 2: "WEDNESDAY", 3: "THURSDAY", 4: "FRIDAY", 5: "SATURDAY", 6: "SUNDAY"}
    day = d[day_number]
    print(day)

08 05 2015
WEDNESDAY


##### Time Delta

found the dateutil.parser.parse() function in the Discussions Section

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

import datetime
import dateutil.parser

# Complete the time_delta function below.
def time_delta(t1, t2):
    t1 = dateutil.parser.parse(t1,fuzzy=True)
    t2 = dateutil.parser.parse(t2,fuzzy=True)
    
    seconds = abs(t1-t2).total_seconds()
    seconds = int(seconds)
    time_diff_sec = str(seconds)
    return time_diff_sec
   

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()


In [58]:
#!/bin/python3

import math
import os
import random
import re
import sys

import datetime
import dateutil.parser

# Complete the time_delta function below.
def time_delta(t1, t2):
    t1 = dateutil.parser.parse(t1,fuzzy=True)
    t2 = dateutil.parser.parse(t2,fuzzy=True)
    
    seconds = abs(t1-t2).total_seconds()
    seconds = int(seconds)
    time_diff_sec = str(seconds)
    return time_diff_sec
   

t = int(input())

deltas = []
for t_itr in range(t):
    t1 = input()

    t2 = input()

    delta = time_delta(t1, t2)
    deltas.append(delta)

for d in deltas:
    print(d)


2
Sun 10 May 2015 13:54:36 -0700
Sun 10 May 2015 13:54:36 -0000
Sat 02 May 2015 19:54:36 +0530
Fri 01 May 2015 13:54:36 -0000
25200
88200


# Exceptions (only 1 - max points: 10)
https://www.hackerrank.com/challenges/exceptions


##### Exceptions

In [59]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

T = int(input())

numbers = []
for i in range(T):
    a_b = list(map(str, input().split()))
    numbers.append(a_b)

if (T<=0) or (T>=100):
    print('')
else:
    for n in numbers:
        try:
            a = int(n[0])
            b = int(n[1])
            print(int(a/b))
        except ZeroDivisionError as zd:
            print("Error Code:", 'integer division or modulo by zero')
        except ValueError as ve:
            print("Error Code:",ve)

3
1 0
2 $
3 1
Error Code: integer division or modulo by zero
Error Code: invalid literal for int() with base 10: '$'
3


# Built-ins (only 3 - max points: 80)
https://www.hackerrank.com/challenges/zipped

##### Zipped!

In [60]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

N_X = list(map(int, input().split()))
N = N_X[0]
X = N_X[1]

grades_by_subj = []
for i in range(X):
    grades = list(map(float, input().split()))
    grades_by_subj.append(grades)

if (N<=0) or (N>100):
    print('')
elif (X<=0) or (X>100):
    print('')
else:
    for i in range(N):
        grades_person = 0
        for subj in range(X):
            grades_person += grades_by_subj[subj][i]
        
        average_grade = grades_person / X
        print("{:.1f}".format(average_grade))

5 3
89 90 78 93 80
90 91 85 88 86 
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


##### Athlete Sort

In [61]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())
        
    sorted_table = arr.sort(key = lambda x: x[k])
    
    for i in arr:
        print(" ".join(map(str, i)))


5 3
10 2 5
7 1 0
9 9 9 
1 23 12 
6 5 9
1
7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


##### ginortS

In [62]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

S = str(input())

if S.isalnum == False:
    print('')
elif (len(S)<=0) or (len(S)>=1000):
    print('')
else:
    list_lower = []
    list_upper = []
    list_odd = []
    list_even = []
    
    for elem in S:
        if elem.islower() == True:
            list_lower.append(elem)
        elif elem.isupper() == True:
            list_upper.append(elem)
        elif elem.isdigit() == True:
            if int(elem)%2 == 0:
                list_even.append(elem)
            else:
                list_odd.append(elem)
    
    list_lower.sort()
    list_upper.sort()
    list_odd.sort()
    list_even.sort()
    
    new_string = ''
    for i in list_lower:
        new_string += i
    for j in list_upper:
        new_string += j
    for k in list_odd:
        new_string += k
    for z in list_even:
        new_string += z
        
    print(new_string)

Sorting1234
ginortS1324


# Python Functionals (only 1 - max points: 20)
https://www.hackerrank.com/challenges/map-and-lambda-expression

##### Map and Lambda Function

In [64]:
# complete the lambda function 
cube = lambda x: x**3


def fibonacci(n):
    # return a list of fibonacci numbers
    if (n<0) or (n>15):
        print('')
    else:
        if n==0:
            fibonacci_numbers = []
        elif n==1:
            fibonacci_numbers = [0]
        elif n==2:
            fibonacci_numbers = [0,1]
        else:
            fibonacci_numbers = [0,1]
            for i in range(2,n):
                new_number = fibonacci_numbers[i-1] + fibonacci_numbers[i-2]
                fibonacci_numbers.append(new_number)
        
        return fibonacci_numbers
    
    
    

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


# Regex and Parsing challenges (all – total: 17 - max points: 560)
https://www.hackerrank.com/domains/python/py-regex

##### Detect Floating Point Number

In [234]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

# number of test cases
T = int(input())

if (T<=0) or (T>=10):
    print("")
else:
    numbers = []
    for i in range(T):
        numbers.append(list(map(str,input().split()))[0])
    
    for n in numbers:
        try:
            float(n)
        except:
            print("False")
            continue
            
        if '.' not in n:
            print('False')
        elif ('-' in n) and ('+' in n):
            print('False')
        elif (n.count('-')>1) or (n.count('+')>1) or (n.count('.')>1):
            print('False')
        elif n[-1] == '.':
            print('False')
        else:
            print("True")
    

4
4.0O0
-1.00 
+4.54
SomeRandomStuff
False
True
True
False


##### Re.split()

In [235]:
regex_pattern = r"[,.]"	# Do not delete 'r'.

import re
print("\n".join(re.split(regex_pattern, input())))

100,000,000.000
100
000
000
000


##### Group(), Groups() & Groupdict()

In [236]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

S = str(input())

if (len(S)<=0) or (len(S)>=100):
    print('')
else:
    # first check if there are no repeating characters
    if len(set(S)) == len(S):
         print(-1)
    else:
        #not_alphanum = 0
        for i in range(len(S)-1):
            if S[i].isalnum() == True:
                if S[i] == S[i+1]:
                    print(S[i])
                    break
            if (i == len(S)-2):
                print(-1)
   

..12345678910111213141516171820212223
1


##### Re.findall() & Re.finditer()

In [244]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

# ?<= lookbehind
# ?= lookahead
#([AEIOUaeiou]{2,}) find 2 or more vowels

import re
S = str(input())

if (len(S)<=0) or (len(S)>=100):
    print('')
else:
    S.strip()
    found_pattern = re.finditer(r'(?<=[QWRTYPSDFGHJKLZXCVBNMqwrtypsdfghjklzxcvbnm])([AEIOUaeiou]{2,})(?=[QWRTYPSDFGHJKLZXCVBNMqwrtypsdfghjklzxcvbnm])', S)
    
    groups_vowels = []
    for i in map(lambda x: x.group(), found_pattern):
        groups_vowels.append(i)
    
    if groups_vowels == []:
            print(-1)
    else:
        for p in groups_vowels:
            print(p)
    

rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


##### Re.start() & Re.end()

In [239]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

S = str(input())
k = str(input())

if (len(S)<=0) or (len(S)>=100):
    print("")
elif (len(k)<=0) or (len(k)>=len(S)):
    print("")
elif k not in S:
    print("(-1, -1)")
else:
    for m in re.finditer(rf"(?={k})", S):
        print("(" + str(m.start()) + ", " + str(m.end()+len(k)-1) + ")")


aaadaa
aa
(0, 1)
(1, 2)
(4, 5)


##### Regex Substitution

In [247]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

N = int(input())
if (N<=0) or (N>=100):
    print('')
else:
    text = [input() for _ in range(N)]
    
    assert all((t[0:2] != '&&') and (t[0:2] != '||') for t in text)
    assert all((t[-2:] != '&&') and (t[-2:] != '||') for t in text)
    
    
    for t in text:
        t2 = re.sub(r"(?<= )&&(?= )", 'and', t)
        t3 = re.sub(r"(?<= )(\|\|)(?= )", "or", t2)
        print(t3)


1
n && && && && && &&n
n and and and and and &&n


##### Validating Roman Numerals

In [237]:
# The symbols are I, V, X, L, C, D, and M, standing respectively for 1, 5, 10, 50, 100, 500, and 1,000 

# 1000-3000
thousands = "M{0,3}"

# 100-300, 400, 500-800, 900
hundreds = "(D?C{0,3}|C[DM])"

# 10-30, 40, 50-80, 90
tens = "(L?X{0,3}|X[LC])"

# 1-3, 4 , 5-8, 9
units = "(V?I{0,3}|I[VX])"

regex_pattern = r"%s%s%s%s$" % (thousands,hundreds,tens,units) # Do not delete 'r'.


import re
print(str(bool(re.match(regex_pattern, input()))))

CDXXI
True


##### Validating phone numbers

In [238]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

# A valid mobile number is a ten digit number starting with a 7,8, or 9

# number of phone numbers
N = int(input())

if (N<1) or (N>10):
    print('')
else:
    phone_num = [str(input()) for _ in range(N)]
    
    assert all((len(p)>=2) or (len(p)<=15) for p in phone_num)
    
    for pn in phone_num:
        try:
            int(pn)
        except:
            print("NO") 
            continue
        
        if len(pn) == 10:
            if pn[0] in ["7","8","9"]:
                print("YES")
            else:
                print("NO")
        else:
            print("NO")


2
9587456281
1252478965
YES
NO


##### Validating and Parsing Email Addresses

In [245]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

# ? matches either once or zero times

# * matches zero or more times the group that precedes the star

# + matches one or more times the group that precedes the star

# \w matches any alphanumeric character. If the regex pattern is expressed in bytes, this is equivalent to the class [a-zA-Z0-9_]. 


import re
import email.utils

# number of emails
n = int(input())

if (n<=0) or (n>=100):
    print('')
else:
    name_email = [input().split() for _ in range(n)]
     
    reg_pattern = r'<[a-zA-Z][\w\-\.\_]+\@[a-zA-Z]+\.[a-zA-Z]{1,3}>' 

    
    for i in name_email:
        if bool(re.match(reg_pattern, i[1])) == True:
            print(i[0], i[1])     
    

2
DEXTER <dexter@hotmail.com>
VIRUS <virus!@variable.:p>
DEXTER <dexter@hotmail.com>


##### Hex Color Code

The "reg_pat_1 = "\{[^\{\}]+\}"" that I have used I saw on the Discussion section

In [261]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

N = int(input())

if (N<=0) or (N>=50):
    print('')
else:
    text = [input() for _ in range(N)]
    new_str_1 = "".join(text)
    
    reg_pat_1 = "\{[^\{\}]+\}"
    
    new_str_2 = re.findall(reg_pat_1,new_str_1)
    
    reg_pat_2 = r"\#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})\b"
    
    for n in new_str_2:
        if len(n) != 0:
            found_pattern = re.findall(reg_pat_2, n)
            for f in range(len(found_pattern)):
                print(f'#{found_pattern[f]}')


6
#BED
{
color: #FfFdF8; background-color:#aef;     
font-size: 123px;     
background: -webkit-linear-gradient(top, #f9f9f9, #fff); }
}
#FfFdF8
#aef
#f9f9f9
#fff


##### HTML Parser - Part 1

In [250]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print("Start :", tag)
        for name,value in attrs:
            print(f"-> {name} > {value}")

    def handle_endtag(self, tag):
        print("End   :", tag)
        
    def handle_startendtag(self, tag, attrs):
        print("Empty :", tag)
        for name,value in attrs:
            print(f"-> {name} > {value}")
            

parser = MyHTMLParser()
            
N = int(input())

if (N<=0) or (N>=100):
    print('')
else:
    html_code = [input() for _ in range(N)]
    
    for h in html_code:
        parser.feed(h)


2
<html><head><title>HTML Parser - I</title></head>
<body data-modal-target class='1'><h1>HackerRank</h1><br /></body></html>
Start : html
Start : head
Start : title
End   : title
End   : head
Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html


##### HTML Parser - Part 2

In [251]:
from html.parser import HTMLParser
import re

class MyHTMLParser(HTMLParser):
    def handle_comment(self, data):
        if re.search(r"\n", data):
            print(">>> Multi-line Comment")
            print(data)
        else:
            print(">>> Single-line Comment")
            print(data)
            
    def handle_data(self, data):
        if data != '\n':
            print(">>> Data")
            print(data)  
    
  
  
html = ""       
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()


4
<!--[if IE 9]>IE9-specific content
<![endif]-->
<div> Welcome to HackerRank</div>
<!--[if IE 9]>IE9-specific content<![endif]-->
>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Data
 Welcome to HackerRank
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]


##### Detect HTML Tags, Attributes and Attribute Values

In [252]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

from html.parser import HTMLParser
import re

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(tag)
        for name,value in attrs:
            print(f"-> {name} > {value}")
        
    def handle_startendtag(self, tag, attrs):
        print(tag)
        for name,value in attrs:
            print(f"-> {name} > {value}")
    
  
  
html = ""       
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()

9
<head> 
<title>HTML</title> 
</head>
<object type="application/x-flash" 
  data="your-file.swf" 
  width="0" height="0">
  <!-- <param name="movie" value="your-file.swf" /> -->
  <param name="quality" value="high"/>
</object>
head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


##### Validating UID

In [253]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

T = int(input())

ID_list = [input() for _ in range(T)]

for ID in ID_list:
    if len(ID) != 10:
        print('Invalid')
    elif len(set(ID)) != 10:
        print('Invalid')
    elif ID.isalnum() == False:
        print('Invalid')
    else:
        num_upper = 0
        num_digits = 0
        for i in range(len(ID)):
            if ID[i].isupper():
                num_upper += 1
            if ID[i].isnumeric():
                num_digits += 1
        
        if (num_upper >= 2) and (num_digits >= 3):
            print('Valid')
        else:
            print('Invalid')
        

2
B1CD102354
B1CDEF2354
Invalid
Valid


##### Validating Credit Card Numbers

In [255]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

N = int(input())

if (N<=0) or (N>=100):
    print('')
else:
    card_numbers = [input().strip() for _ in range(N)]
    
    reg_pat_1 = r'^[456]([0-9]{15}\b)'
    
    reg_pat_2 = r'^[456]([0-9]{3})\-([0-9]{4})\-([0-9]{4})\-([0-9]{4})'
    
    reg_pat_3 = r"([0-9])(-?\1){3}"
    
    for c in card_numbers:
        if bool(re.fullmatch(reg_pat_1,c)):
            if bool(re.search(reg_pat_3, c)):
                print('Invalid')
            else:
                print('Valid')
        elif bool(re.fullmatch(reg_pat_2,c)):
            if bool(re.search(reg_pat_3, c)):
                print('Invalid')
            else:
                print('Valid')
        else:
            print('Invalid')        


6
4123456789123456 
5123-4567-8912-3456 
61234-567-8912-3456 
4123356789123456 
5133-3367-8912-3456 
5123 - 3567 - 8912 - 3456
Valid
Valid
Invalid
Valid
Invalid
Invalid


##### Validating Postal Codes

In [265]:
regex_integer_in_range = r"(\b[1-9][0-9][0-9][0-9][0-9][0-9]\b)" # Do not delete 'r'.

regex_alternating_repetitive_digit_pair = r"(\d)(?=\d\1)"	# Do not delete 'r'.



import re
P = input()

print (bool(re.match(regex_integer_in_range, P)) 
and len(re.findall(regex_alternating_repetitive_digit_pair, P)) < 2)

110000
False


##### Matrix Script

In [257]:
#!/bin/python3

import math
import os
import random
import re
import sys




first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)

string = ''
for j in range(m):
    for i in range(n):
        string += matrix[i][j]
        
reg_pattern = r"(?<=\w)[!@#$%& ]{1,}(?=\s*\w)"        
new_str = re.sub(reg_pattern, ' ', string)
print(new_str)

7 3 
Tsi
h%x
i #
sM 
$a 
#t%
ir!
This is Matrix#  %!


# XML (all – total: 2 - max points: 40)
https://www.hackerrank.com/domains/python/xml


##### XML 1 - Find the Score

In [ ]:
import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    # your code goes here
    total = len(node.attrib)
    
    for child in node:
        total += get_attr_number(child)
    
    return total


if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

##### XML2 - Find the Maximum Depth

In [ ]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    
    level += 1
    
    for child in elem:
        depth_child = depth(child,level)
        if depth_child > maxdepth:
            maxdepth = depth_child
        
    return level

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

# Closures and Decorations (all – total: 2 - max points: 60)
https://www.hackerrank.com/domains/python/closures-and-decorators

##### Standardize Mobile Number Using Decorators

In [3]:
def wrapper(f):
    def fun(l):
        # complete the function
        new_list = []
        
        for i in l:
            if len(i) == 10:
                phone = '+91 ' + i[:5] + ' ' + i[5:]
                new_list.append(phone)
            elif len(i) == 11:
                phone = '+91 ' + i[1:6] + ' ' + i[6:]
                new_list.append(phone)
            elif len(i) == 12:
                phone = '+91 ' + i[2:7] + ' ' + i[7:]
                new_list.append(phone)
            elif len(i) == 13:
                phone = '+91 ' + i[3:8] + ' ' + i[8:]
                new_list.append(phone)
        
        f(new_list)
                
    return fun


@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

3
07895462130
919875641230
9195969878
+91 78954 62130
+91 91959 69878
+91 98756 41230


##### Decorators 2 - Name Directory

In [132]:
import operator

def person_lister(f):
    def inner(people):
        # complete the function
        if len(people)>10:
            return("")
        else:
            for i in people:
                i[2] = int(i[2])
            people.sort(key = lambda x: x[2])
            
            new_list = []
            for i in people:
                name = f(i)
                new_list.append(name)
                
            return new_list    
        
    return inner



@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


# Numpy (all – total: 15 - max points: 300)
https://www.hackerrank.com/domains/python/numpy

##### Arrays

In [14]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    
    arr.reverse()
    rev_float = numpy.array(arr, float)
    return rev_float

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


##### Shape and Reshape

In [65]:
import numpy

list_int = list(map(int, input().split()))

new_array = numpy.reshape(list_int,(3,3))
print(new_array)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### Transpose and Flatten

In [70]:
import numpy

n_m = list(map(int, input().split()))
N = n_m[0]
M = n_m[1]

array = []
for _ in range(N):
    elem = list(map(int, input().split()))
    array.append(elem)
    
np_arr = numpy.array(array)
    
print(numpy.transpose(np_arr))
print(np_arr.flatten())



2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


##### Concatenate

In [71]:
import numpy

nmp = list(map(int, input().split()))
N = nmp[0]
M = nmp[1]
P = nmp[2]

N_list = numpy.array([])
for _ in range(N):
    elem = list(map(int, input().split()))
    N_list = numpy.append(N_list, numpy.array(elem))

M_list = numpy.array([])
for _ in range(M):
    elem = list(map(int, input().split()))
    M_list = numpy.append(M_list, numpy.array(elem))
    
d1 = N+M
new_array = numpy.concatenate((N_list, M_list))
new_array = new_array.astype(int)
print(numpy.reshape(new_array, (d1,P)))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


##### Zeros and Ones

In [93]:
import numpy

integers = list(map(int, input().split()))

if (min(integers)<1) or (max(integers)>3):
    print('')
else:
    array_0 = numpy.zeros(integers,int)   
    array_1 = numpy.ones(integers,int)   
        
    print(array_0)
    print(array_1)


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


##### Eye and Identity

In [72]:
import numpy
numpy.set_printoptions(legacy='1.13')

nm = list(map(int, input().split()))
N = nm[0] #rows
M = nm[1] #cols

print(numpy.eye(N, M, k = 0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


##### Array Mathematics

In [73]:
import numpy as np

nm = list(map(int, input().split()))
N = nm[0]
M = nm[1]

A = []
for i in range(N):
    elem = list(map(int, input().split()))
    A.append(elem)
A = np.array(A)

B = []
for i in range(N):
    elem = list(map(int, input().split()))
    B.append(elem)
B = np.array(B)

if (len(A[0]) != M) or (len(B[0]) != M):
    print('')
else:
    print(A+B)
    print(A-B)
    print(A*B)
    print(np.floor_divide(A,B))
    print(A%B)
    print(A**B) 

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


##### Floor, Ceil and Rint

In [74]:
import numpy as np
np.set_printoptions(legacy='1.13')


A = list(map(float, input().split()))
arr = np.array(A)

print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


##### Sum and Prod

In [81]:
import numpy as np

nm = list(map(int, input().split()))
N = nm[0]
M = nm[1]

if (N==0) or (M==0):
    print('')
else:
    A = []
    for i in range(N):
        elem = list(map(int, input().split()))
        A.append(elem)
    A = np.array(A)


    len_elem = list(map(len,A))
    max_len = max(len_elem)
    min_len = min(len_elem)

    if (max_len!=M) or (min_len!=M):
        print('')
    else:
        sum_arr_ax0 = np.sum(A, axis=0)

        print(np.prod(sum_arr_ax0))

2 2
1 2
3 4
24


##### Min and Max

In [82]:
import numpy as np

nm = list(map(int, input().split()))
N = nm[0]
M = nm[1]

if (N==0) or (M==0):
    print('')
else:
    A = []
    for i in range(N):
        elem = list(map(int, input().split()))
        A.append(elem)
    A = np.array(A)
    
    len_elem = list(map(len,A))
    max_len = max(len_elem)
    min_len = min(len_elem)

    if (max_len!=M) or (min_len!=M):
        print('')
    else:
        min_ax1 = np.min(A, axis=1)
        print(np.max(min_ax1))



4 2
2 5
3 7
1 3
4 0
3


##### Mean, Var, and Std

In [92]:
import numpy as np

nm = list(map(int, input().split()))
N = nm[0]
M = nm[1]

if (N==0) or (M==0):
    print('')
else:
    A = []
    for i in range(N):
        elem = list(map(int, input().split()))
        A.append(elem)
    A = np.array(A)
    
    len_elem = list(map(len,A))
    max_len = max(len_elem)
    min_len = min(len_elem)

    if (max_len!=M) or (min_len!=M):
        print('')
    else:
        mean_ax1 = np.mean(A, axis=1)
        var_ax0 = np.var(A, axis=0)
        std_axN = np.std(A, axis=None)
        
        print(mean_ax1)
        print(var_ax0)
        print(round(std_axN,11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


##### Dot and Cross

In [87]:
import numpy as np

N = int(input())

if N == 0:
    print('')
else:
    A = []
    for i in range(N):
        elem = list(map(int, input().split()))
        A.append(elem)
    A = np.array(A)

    B = []
    for i in range(N):
        elem = list(map(int, input().split()))
        B.append(elem)
    B = np.array(B)

    len_elem_A = list(map(len,A))
    max_len_A = max(len_elem_A)
    min_len_A = min(len_elem_A)

    len_elem_B = list(map(len,B))
    max_len_B = max(len_elem_B)
    min_len_B = min(len_elem_B)

    if (max_len_A!=N) or (min_len_A!=N) or (max_len_B!=N) or (min_len_B!=N):
        print('')
    else:
        print(np.dot(A,B))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


##### Inner and Outer

In [88]:
import numpy as np

A = list(map(int, input().split()))
B = list(map(int, input().split()))

A_arr = np.array(A)
B_arr = np.array(B)

if (len(A)) != (len(B)):
    print('')
else:
    print(np.inner(A,B))
    print(np.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


##### Polynomials

In [89]:
import numpy as np


coeff_P = list(map(float, input().split()))
x = float(input())

print(np.polyval(coeff_P, x))

1.1 2 3
0
3.0


##### Linear Algebra

In [91]:
import numpy as np

N = int(input())

if N == 0:
    print('')
else:
    A = []
    for i in range(N):
        elem = list(map(float, input().split()))
        A.append(elem)
    A = np.array(A)

    determinant = np.linalg.det(A)

    if determinant%1 == 0:
        print("{:.1f}".format(determinant))
    else:
        print("{:.2f}".format(determinant))

3
1 2 3
4 5 6
1 2 1
6.0


-------------------------

# Problem 2

#### birthday-cake-candles 
https://www.hackerrank.com/challenges/birthday-cake-candles

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'birthdayCakeCandles' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY candles as parameter.
#

def birthdayCakeCandles(candles):
    # Write your code here
   
    tallest = max(candles)
    num_tallest = candles.count(tallest)
            
    return num_tallest
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    candles_count = int(input().strip())

    candles = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(candles)

    fptr.write(str(result) + '\n')

    fptr.close()

#### kangaroo 
https://www.hackerrank.com/challenges/kangaroo

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'kangaroo' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER x1
#  2. INTEGER v1
#  3. INTEGER x2
#  4. INTEGER v2
#

def kangaroo(x1, v1, x2, v2):
    # Write your code here
    # the first 3 "is" are the constraints
    if (x1<0) or (x1>=x2) or (x2>10000):
        return("NO")
    elif (v1<1) or (v1>10000):
        return("NO")
    elif (v2<1) or (v2>10000):
        return("NO")
    elif v2>=v1:
        return("NO")
    else:
        while True:
            if x1 == x2:
                return("YES")
            elif x1 > x2:
                return("NO")
            else:
                x1 += v1
                x2 += v2
      
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    x1 = int(first_multiple_input[0])

    v1 = int(first_multiple_input[1])

    x2 = int(first_multiple_input[2])

    v2 = int(first_multiple_input[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()


#### strange-advertising
https://www.hackerrank.com/challenges/strange-advertising

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'viralAdvertising' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#

def viralAdvertising(n):
    # Write your code here
    
    if (n<1) or (n>50):
        return("")
    else:
        shared = 5
        cumulative = 0
        for i in range(n): 
            liked = shared//2
            cumulative += liked
            shared = liked*3
    return cumulative
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()

#### recursive-digit-sum
https://www.hackerrank.com/challenges/recursive-digit-sum

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n, k):
    # Write your code here
    if (len(n)==1) and (k==1):
        return(int(n))
    else:
        sum_dig = 0
        for i in range(len(n)):
            sum_dig+=int(n[i])
        return superDigit(str(sum_dig*k),1)
        
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()


#### insertionsort1
https://www.hackerrank.com/challenges/insertionsort1

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    if (n<1) or (n>1000):
        print("")
    else:
        x = arr[-1]
        
        for i in range(n-1, -1, -1):
            if (arr[i-1] > x) and (i>=1):
                arr[i] = arr[i-1]
                print(" ".join(map(str,arr)))
            else:
                arr[i] = x
                print(" ".join(map(str,arr)))
                break    
        

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)


#### insertionsort2
https://www.hackerrank.com/challenges/insertionsort2

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort2' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort2(n, arr):
    # Write your code here
    if (n<1) or (n>1000):
        print("")
    else:
        for i in range(1,len(arr)):
            X = arr[i]
            j = i-1
            while (j>=0) and (arr[j]>X):
                arr[j+1] =  arr[j]
                j -= 1
            
            arr[j+1] = X
            print(" ".join(map(str,arr)))
    
    

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort2(n, arr)
